<?php
namespace Tests\Feature\Coach;
use App\Coach\AI\AIProviderInterface; use App\Coach\AI\FakeAIProvider; use App\Coach\Services\CareerCoachService; use App\Coach\Services\CoachSettingsService;
use App\Http\Middleware\OnlyTestUsers; use App\Models\CareerGoal; use App\Models\CoachUsage; use App\Models\ProfessionalProfile; use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Cache; use Illuminate\Support\Str; use Tests\TestCase;
class CareerGoalTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->withoutMiddleware(OnlyTestUsers::class);Cache::forget('coach_settings');app(CoachSettingsService::class)->update(['enabled'=>true,'module_career'=>true,'monthly_message_limit'=>100,'rate_limit_per_minute'=>100,'languages'=>['fr','de','en']]);}
 public function test_goal_analysis_gaps_roles_and_plan_are_created():void{$user=User::factory()->create();$this->actingAs($user)->post(route('coach.career.store'),$this->payload())->assertRedirect();$goal=CareerGoal::firstOrFail();$this->assertSame('active',$goal->status);$this->assertSame(0,$goal->progress);$this->assertSame('career',$goal->conversation->module);$this->assertCount(2,$goal->actions);$this->assertSame('proposed',$goal->actions->first()->source);$this->assertNotEmpty($goal->analysis['situation']['transferable_skills']);$this->assertNotEmpty($goal->analysis['gaps']['missing_skills']);$this->assertNotEmpty($goal->analysis['roles']['recommended_roles']);foreach(['career.analyze_situation','career.gap_analysis','career.explore_roles','career.build_action_plan'] as $op)$this->assertDatabaseHas('coach_usages',['operation'=>$op,'status'=>'success','prompt_version'=>'1.0']);}
 public function test_goal_works_without_profile_and_never_changes_profile():void{$user=User::factory()->create();$goal=app(CareerCoachService::class)->create($user,$this->payload());$this->assertNull($user->professionalProfile);$this->assertNotNull($goal->analysis);ProfessionalProfile::factory()->for($user)->create(['professional_title'=>'Comptable']);app(CareerCoachService::class)->factsContext($user,$goal);$this->assertDatabaseHas('professional_profiles',['user_id'=>$user->id,'professional_title'=>'Comptable']);}
 public function test_manual_action_update_completion_reopen_and_progress_are_server_side():void{$user=User::factory()->create();$goal=app(CareerCoachService::class)->create($user,$this->payload());$this->actingAs($user)->post(route('coach.career.actions.store',$goal),['title'=>'Action manuelle','priority'=>'high','due_date'=>'2026-12-01'])->assertRedirect();$manual=$goal->actions()->where('source','manual')->firstOrFail();$this->assertSame(3,$goal->actions()->count());$this->actingAs($user)->patch(route('coach.career.actions.update',[$goal,$manual]),['title'=>'Action modifiée','priority'=>'low','status'=>'completed'])->assertRedirect();$this->assertSame('Action modifiée',$manual->fresh()->title);$this->assertSame(33,$goal->fresh()->progress);$this->actingAs($user)->patch(route('coach.career.actions.update',[$goal,$manual]),['status'=>'todo'])->assertRedirect();$this->assertSame(0,$goal->fresh()->progress);$this->assertNull($manual->fresh()->completed_at);$this->assertSame(4,CoachUsage::count());}
 public function test_owner_can_revise_goal_without_provider_usage():void{$user=User::factory()->create();$goal=app(CareerCoachService::class)->create($user,$this->payload());$usage=CoachUsage::count();$this->actingAs($user)->patch(route('coach.career.update',$goal),['title'=>'Objectif révisé','current_situation'=>'Nouvelle situation','target_role'=>'Lead Product','target_sector'=>'SaaS','target_description'=>'Cible révisée','language'=>'de','target_date'=>'2028-01-31'])->assertRedirect();$goal->refresh();$this->assertSame('Objectif révisé',$goal->title);$this->assertSame('Lead Product',$goal->target_role);$this->assertSame('de',$goal->language);$this->assertSame($usage,CoachUsage::count());}
 public function test_completing_all_actions_completes_goal_and_reopening_reactivates_it():void{$user=User::factory()->create();$goal=app(CareerCoachService::class)->create($user,$this->payload());foreach($goal->actions as $action)$this->actingAs($user)->patch(route('coach.career.actions.update',[$goal,$action]),['status'=>'completed'])->assertRedirect();$this->assertSame(100,$goal->fresh()->progress);$this->assertSame('completed',$goal->fresh()->status);$this->assertNotNull($goal->fresh()->completed_at);$first=$goal->actions()->first();$this->actingAs($user)->patch(route('coach.career.actions.update',[$goal,$first]),['status'=>'in_progress']);$this->assertSame('active',$goal->fresh()->status);$this->assertNull($goal->fresh()->completed_at);}
 public function test_foreign_user_and_admin_cannot_access_goal_action_or_conversation():void{$owner=User::factory()->create();$goal=app(CareerCoachService::class)->create($owner,$this->payload());$action=$goal->actions()->first();foreach([User::factory()->create(),User::factory()->create(['role'=>'admin'])] as $intruder){$this->actingAs($intruder)->get(route('coach.career.show',$goal))->assertNotFound();$this->actingAs($intruder)->patch(route('coach.career.update',$goal),['title'=>'Intrusion','language'=>'fr'])->assertNotFound();$this->actingAs($intruder)->patch(route('coach.career.actions.update',[$goal,$action]),['status'=>'completed'])->assertNotFound();$this->actingAs($intruder)->post(route('coach.conversations.messages.store',$goal->conversation),['content'=>'Intrusion'])->assertNotFound();}}
 public function test_module_disabled_and_quota_block_provider_calls():void{$user=User::factory()->create();app(CoachSettingsService::class)->update(['module_career'=>false]);$this->actingAs($user)->get(route('coach.career.index'))->assertForbidden();$this->actingAs($user)->post(route('coach.career.store'),$this->payload())->assertForbidden();$this->assertSame(0,CoachUsage::count());app(CoachSettingsService::class)->update(['module_career'=>true,'monthly_message_limit'=>1]);CoachUsage::factory()->for($user)->create(['coach_conversation_id'=>null]);$this->actingAs($user)->post(route('coach.career.store'),$this->payload())->assertTooManyRequests();$this->assertDatabaseMissing('career_goals',['status'=>'completed']);}
 public function test_provider_error_and_invalid_structure_leave_draft_not_completed():void{$user=User::factory()->create();$this->app->instance(AIProviderInterface::class,new FakeAIProvider('error'));$this->actingAs($user)->post(route('coach.career.store'),$this->payload())->assertSessionHas('error');$this->assertDatabaseHas('career_goals',['status'=>'draft']);$this->app->instance(AIProviderInterface::class,new FakeAIProvider('invalid'));$this->actingAs($user)->post(route('coach.career.store'),$this->payload())->assertSessionHas('error');$this->assertSame(0,CareerGoal::where('status','completed')->count());}
 public function test_duplicate_submission_is_idempotent():void{$user=User::factory()->create();$data=$this->payload();$service=app(CareerCoachService::class);$a=$service->create($user,$data);$count=CoachUsage::count();$b=$service->create($user,$data);$this->assertSame($a->id,$b->id);$this->assertSame(1,CareerGoal::count());$this->assertSame($count,CoachUsage::count());$this->assertSame(1,$user->coachConversations()->where('module','career')->count());}
 private function payload():array{return ['title'=>'Devenir Product Manager','current_situation'=>'Comptable avec expérience client','target_role'=>'Product Manager','target_sector'=>'Technologie','target_description'=>'Transition progressive','language'=>'fr','target_date'=>'2027-06-30','submission_token'=>(string)Str::uuid()];}
}
