<?php
namespace Tests\Feature\Coach;
use App\Coach\AI\AIProviderInterface; use App\Coach\AI\FakeAIProvider; use App\Coach\Services\CertificationCoachService; use App\Coach\Services\CoachSettingsService; use App\Http\Middleware\OnlyTestUsers; use App\Models\CareerGoal; use App\Models\CoachAnalysis; use App\Models\CoachUsage; use App\Models\ProfessionalProfile; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Cache; use Illuminate\Support\Str; use Inertia\Testing\AssertableInertia as Assert; use Tests\TestCase;
class CertificationAnalysisTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->withoutMiddleware(OnlyTestUsers::class);Cache::forget('coach_settings');app(CoachSettingsService::class)->update(['enabled'=>true,'module_certification'=>true,'monthly_message_limit'=>100,'rate_limit_per_minute'=>100,'languages'=>['fr','de','en']]);}
 public function test_full_skills_certification_and_learning_plan_analysis():void{$user=User::factory()->create();ProfessionalProfile::factory()->for($user)->create(['professional_title'=>'Développeur']);$this->actingAs($user)->post(route('coach.certifications.store'),$this->payload())->assertRedirect();$a=CoachAnalysis::firstOrFail();$this->assertSame('certification',$a->module);$this->assertSame('completed',$a->status);$this->assertSame('skills_gap',$a->analysis_type);$this->assertNotEmpty($a->result['skills']['missing_skills']);$this->assertSame('high',$a->result['skills']['priority_skills'][0]['priority']);$this->assertNotEmpty($a->result['recommendations']['recommendations']);$this->assertStringContainsString('vérifier',$a->result['recommendations']['recommendations'][0]['notes']);$this->assertNotEmpty($a->result['recommendations']['training_suggestions']);$this->assertCount(2,$a->result['plan']['steps']);$this->assertSame('certification',$a->conversation->module);foreach(['certification.skills_gap','certification.recommend','certification.learning_plan'] as $op)$this->assertDatabaseHas('coach_usages',['operation'=>$op,'status'=>'success','prompt_version'=>'1.0']);}
 public function test_owned_active_career_goal_is_context_only_and_actions_are_unchanged():void{$user=User::factory()->create();$goal=$this->goal($user);$goal->actions()->create(['title'=>'Action existante','priority'=>'medium','status'=>'todo','sort_order'=>1,'source'=>'manual']);$a=app(CertificationCoachService::class)->analyze($user,$this->payload(['career_goal_id'=>$goal->id]));$this->assertSame($goal->id,$a->career_goal_id);$this->assertSame(1,$goal->actions()->count());$context=app(CertificationCoachService::class)->factsContext($user,$a,$goal);$this->assertSame($goal->title,$context['career_goal_facts']['title']);$this->assertStringContainsString('RECOMMENDATION',$context['context_semantics']['recommendations']);}
 public function test_foreign_career_goal_is_rejected_before_analysis():void{$owner=User::factory()->create();$other=User::factory()->create();$foreign=$this->goal($other);$this->actingAs($owner)->post(route('coach.certifications.store'),$this->payload(['career_goal_id'=>$foreign->id]))->assertNotFound();$this->assertSame(0,CoachUsage::count());$this->assertSame(0,CoachAnalysis::count());}
 public function test_history_and_analysis_are_private_even_from_admin():void{$owner=User::factory()->create();$a=app(CertificationCoachService::class)->analyze($owner,$this->payload());$this->actingAs($owner)->get(route('coach.certifications.index'))->assertOk()->assertInertia(fn(Assert $p)=>$p->component('Frontend/Coach/Certifications/Index')->has('analyses.data',1));$this->actingAs($owner)->get(route('coach.certifications.show',$a))->assertOk();foreach([User::factory()->create(),User::factory()->create(['role'=>'admin'])] as $intruder)$this->actingAs($intruder)->get(route('coach.certifications.show',$a))->assertNotFound();}
 public function test_disabled_module_and_quota_block_provider():void{$user=User::factory()->create();app(CoachSettingsService::class)->update(['module_certification'=>false]);$this->actingAs($user)->get(route('coach.certifications.index'))->assertForbidden();$this->actingAs($user)->post(route('coach.certifications.store'),$this->payload())->assertForbidden();$this->assertSame(0,CoachUsage::count());app(CoachSettingsService::class)->update(['module_certification'=>true,'monthly_message_limit'=>1]);CoachUsage::factory()->for($user)->create(['coach_conversation_id'=>null]);$this->actingAs($user)->post(route('coach.certifications.store'),$this->payload())->assertTooManyRequests();$this->assertDatabaseMissing('coach_analyses',['module'=>'certification','status'=>'completed']);}
 public function test_provider_error_and_invalid_structure_never_complete():void{$user=User::factory()->create();$this->app->instance(AIProviderInterface::class,new FakeAIProvider('error'));$this->actingAs($user)->post(route('coach.certifications.store'),$this->payload())->assertSessionHas('error');$this->assertDatabaseHas('coach_analyses',['module'=>'certification','status'=>'failed']);$this->app->instance(AIProviderInterface::class,new FakeAIProvider('invalid'));$this->actingAs($user)->post(route('coach.certifications.store'),$this->payload())->assertSessionHas('error');$this->assertSame(0,CoachAnalysis::where('module','certification')->where('status','completed')->count());}
 public function test_submission_replay_is_idempotent_and_profile_is_not_modified():void{$user=User::factory()->create();ProfessionalProfile::factory()->for($user)->create(['professional_title'=>'Comptable']);$data=$this->payload();$service=app(CertificationCoachService::class);$first=$service->analyze($user,$data);$count=CoachUsage::count();$second=$service->analyze($user,$data);$this->assertSame($first->id,$second->id);$this->assertSame(1,CoachAnalysis::where('module','certification')->count());$this->assertSame($count,CoachUsage::count());$this->assertSame(1,$user->coachConversations()->where('module','certification')->count());$this->assertDatabaseHas('professional_profiles',['user_id'=>$user->id,'professional_title'=>'Comptable']);}
 private function goal(User $user):CareerGoal{$conversation=$user->coachConversations()->create(['module'=>'career','title'=>'Carrière','language'=>'fr','status'=>'active']);return $user->careerGoals()->create(['coach_conversation_id'=>$conversation->id,'title'=>'Objectif produit','current_situation'=>'Comptable','target_role'=>'Product Manager','target_sector'=>'Tech','language'=>'fr','status'=>'active','progress'=>0,'submission_token'=>(string)Str::uuid()]);}
 private function payload(array $overrides=[]):array{return array_merge(['target_role'=>'Cloud Architect','target_sector'=>'Technologie','professional_domain'=>'Cloud','objective'=>'Structurer un parcours réaliste','language'=>'fr','career_goal_id'=>null,'submission_token'=>(string)Str::uuid()],$overrides);}
}
