<?php
namespace App\Http\Controllers\Coach;
use App\Coach\Services\CertificationCoachService; use App\Coach\Services\CoachSettingsService; use App\Http\Controllers\Controller; use App\Http\Requests\Coach\StoreCertificationAnalysisRequest; use Illuminate\Http\Request; use RuntimeException; use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;
class CertificationAnalysisController extends Controller {
 public function index(Request $request,CoachSettingsService $settings){$this->enabled($settings);return inertia('Frontend/Coach/Certifications/Index',['analyses'=>$request->user()->coachAnalyses()->where('module','certification')->latest()->paginate(20)->withQueryString()]);}
 public function create(Request $request,CoachSettingsService $settings){$this->enabled($settings);return inertia('Frontend/Coach/Certifications/Create',['careerGoals'=>$request->user()->careerGoals()->where('status','active')->get(['id','title','target_role']),'languages'=>array_values(array_intersect($settings->all()['languages'],['fr','de','en'])),'defaultLanguage'=>$settings->all()['default_language']]);}
 public function store(StoreCertificationAnalysisRequest $request,CertificationCoachService $service){try{$analysis=$service->analyze($request->user(),$request->validated());if($analysis->status==='failed')return back()->withInput()->with('error','Cette analyse a déjà échoué. Lancez une nouvelle demande.');return redirect()->route('coach.certifications.show',$analysis);}catch(RuntimeException $e){if($e instanceof HttpExceptionInterface)throw $e;return back()->withInput()->with('error','L’analyse a échoué. Aucun résultat incomplet n’est présenté.');}}
 public function show(Request $request,int $analysis,CoachSettingsService $settings){$this->enabled($settings);$model=$request->user()->coachAnalyses()->where('module','certification')->with('careerGoal:id,title')->findOrFail($analysis);$this->authorize('view',$model);return inertia('Frontend/Coach/Certifications/Show',['analysis'=>$model]);}
 private function enabled(CoachSettingsService $settings):void{abort_unless($settings->moduleEnabled('certification'),403,'Le module Compétences & certifications est désactivé.');}
}
