<?php
namespace App\Http\Controllers\Coach;
use App\Http\Controllers\Controller; use App\Http\Requests\Coach\StoreUserDocumentRequest; use App\Models\UserDocument; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage;
class UserDocumentController extends Controller
{
    public function index(Request $request) { return inertia('Frontend/Coach/Documents/Index',['documents'=>$request->user()->coachDocuments()->latest()->get()->makeHidden(['path','disk','sha256'])]); }
    public function store(StoreUserDocumentRequest $request) { $file=$request->file('document'); $path=$file->store('', 'coach_private'); $request->user()->coachDocuments()->create(['type'=>$request->validated('type'),'original_name'=>$file->getClientOriginalName(),'path'=>$path,'disk'=>'coach_private','mime_type'=>$file->getMimeType() ?: 'application/octet-stream','size'=>$file->getSize(),'language'=>$request->validated('language'),'sha256'=>hash_file('sha256',$file->getRealPath()),'status'=>'uploaded']); return back()->with('success','Document ajouté.'); }
    public function download(Request $request, int $document) { $model=$request->user()->coachDocuments()->findOrFail($document); $this->authorize('view',$model); abort_unless(Storage::disk($model->disk)->exists($model->path),404); return Storage::disk($model->disk)->download($model->path,$model->original_name); }
    public function destroy(Request $request, int $document) { $model=$request->user()->coachDocuments()->findOrFail($document); $this->authorize('delete',$model); $inUse=$request->user()->coachAnalyses()->where(fn($query)=>$query->where('cv_document_id',$model->id)->orWhere('job_document_id',$model->id))->exists() || $request->user()->interviewSimulations()->whereJsonContains('document_ids',$model->id)->exists(); abort_if($inUse,409,'Ce document est utilisé par un historique Coach et ne peut pas être supprimé.'); Storage::disk($model->disk)->delete($model->path); $model->delete(); return back()->with('success','Document supprimé.'); }
}
