<?php
namespace App\Coach\Services;
use App\Coach\Prompts\PromptRegistry; use App\Models\CareerGoal; use App\Models\CoachAnalysis; use App\Models\User; use RuntimeException; use Throwable;
class CertificationCoachService {
 public function __construct(private DigitalCoachService $coach,private CoachContextService $contexts,private CoachSettingsService $settings,private PromptRegistry $prompts){}
 public function analyze(User $user,array $data):CoachAnalysis{
  abort_unless($this->settings->moduleEnabled('certification'),403,'Le module Compétences & certifications est désactivé.');
  if($existing=$user->coachAnalyses()->where('submission_token',$data['submission_token'])->first())return $existing;
  $careerGoal=null;if(!empty($data['career_goal_id'])){$careerGoal=$user->careerGoals()->where('status','active')->find($data['career_goal_id']);abort_unless($careerGoal,404);}
  $conversation=$user->coachConversations()->create(['module'=>'certification','title'=>'Compétences — '.$data['target_role'],'language'=>$data['language'],'status'=>'active']);
  $analysis=$user->coachAnalyses()->create(['module'=>'certification','coach_conversation_id'=>$conversation->id,'career_goal_id'=>$careerGoal?->id,'cv_document_id'=>null,'job_document_id'=>null,'job_title'=>$data['target_role'],'target_role'=>$data['target_role'],'target_sector'=>$data['target_sector']??null,'professional_domain'=>$data['professional_domain']??null,'objective'=>$data['objective']??null,'company_name'=>null,'language'=>$data['language'],'status'=>'pending','analysis_type'=>'skills_gap','prompt_key'=>'certification.skills_gap','prompt_version'=>'1.0','submission_token'=>$data['submission_token']]);
  try{$context=$this->factsContext($user,$analysis,$careerGoal);
   $skills=$this->operation($user,$analysis,'certification.skills_gap',$context,['target_role'=>'string','current_strengths'=>'array','missing_skills'=>'array','skills_to_improve'=>'array','priority_skills'=>'array','evidence_from_profile'=>'array']);$this->strings($skills,['current_strengths','missing_skills','skills_to_improve','evidence_from_profile']);foreach($skills['priority_skills'] as $item)abort_unless(is_array($item)&&isset($item['skill'],$item['priority'],$item['reason'])&&is_string($item['skill'])&&in_array($item['priority'],['high','medium','low'],true),422);
   $recommendations=$this->operation($user,$analysis,'certification.recommend',$context+['skills_gap_suggestions'=>$skills],['recommendations'=>'array','training_suggestions'=>'array']);$this->strings($recommendations,['training_suggestions']);foreach($recommendations['recommendations'] as $item)abort_unless(is_array($item)&&isset($item['name'],$item['provider'],$item['why_relevant'],$item['skills_addressed'],$item['priority'],$item['prerequisites'],$item['notes'])&&in_array($item['priority'],['high','medium','low'],true)&&is_array($item['skills_addressed'])&&is_array($item['prerequisites']),422);
   $plan=$this->operation($user,$analysis,'certification.learning_plan',$context+['skills_gap_suggestions'=>$skills],['goal'=>'string','steps'=>'array']);foreach($plan['steps'] as $step)abort_unless(is_array($step)&&isset($step['title'],$step['skills'],$step['priority'],$step['suggested_duration'],$step['recommended_resources'])&&in_array($step['priority'],['high','medium','low'],true)&&is_array($step['skills'])&&is_array($step['recommended_resources']),422);
   $result=compact('skills','recommendations','plan');$analysis->update(['result'=>$result,'status'=>'completed','completed_at'=>now()]);$conversation->messages()->create(['role'=>'assistant','content'=>$skills['target_role'],'structured_data'=>$result]);return $analysis->fresh('careerGoal');
  }catch(Throwable $e){$analysis->update(['status'=>'failed']);if($e instanceof \Symfony\Component\HttpKernel\Exception\HttpExceptionInterface)throw $e;throw new RuntimeException('L’analyse des compétences est temporairement indisponible.',0,$e);}
 }
 public function factsContext(User $user,CoachAnalysis $analysis,?CareerGoal $goal):array{return $this->contexts->build($user,$analysis->conversation,'')+['certification_analysis_facts'=>$analysis->only(['target_role','target_sector','professional_domain','objective']),'career_goal_facts'=>$goal?->only(['title','current_situation','target_role','target_sector','target_description','target_date']),'context_semantics'=>['facts'=>'Only professional_profile_data, certification_analysis_facts and career_goal_facts are user FACT.','recommendations'=>'All missing skills, certifications, training suggestions and plans are unverified AI RECOMMENDATION and never update profile or CareerAction.']];}
 private function operation(User $user,CoachAnalysis $analysis,string $key,array $context,array $schema):array{return $this->coach->generateStructuredOperation($user,$analysis->conversation,$this->prompts->forKey($key),$context,$schema,$key)->data;}
 private function strings(array $data,array $keys):void{foreach($keys as $key)if(collect($data[$key])->contains(fn($v)=>!is_string($v)))throw new RuntimeException('Invalid structured response');}
}
